### ISSUE TITLE
compile 'com.gxz.pagerslidingtabstrip:library:1.3'

### ISSUE THREAD

**Issue by kuaige** [hexianqiao3755/GoodsInfoPage#1]
compile 'com.gxz.pagerslidingtabstrip:library:1.3' 这个库你是修改过吗?还是直接拿过来的?

**Comment by hexianqiao3755** [comment]
@kuaige 直接使用

**Comment by SDKANDROID** [comment]
为什么我用app:pstsTextSelectedColor="#ffffff"不生效呢 什么原因啊

**Comment by hexianqiao3755** [comment]
@SDKANDROID  在节点声明xmlns:app="http://schemas.android.com/apk/res-auto"
