### ISSUE TITLE
为什么首先进来的时候不是在页面顶部

### ISSUE THREAD

**Issue by lqjymt** [hexianqiao3755/GoodsInfoPage#2]
为什么首先进来的时候不是在页面顶部

**Comment by hexianqiao3755** [comment]
@lqjymt  一般不会有这种问题的, 我这边app一直用这个, 没出现你这种情况, 要不你具体描述下

**Comment by lqjymt** [comment]
![screenshot_20170118-150709](https://cloud.githubusercontent.com/assets/19730956/22054325/fb0150bc-dd8f-11e6-8ae0-7ccefb5dcbff.jpg)  就是这样  一进来就显示这里  看不到轮播界面不是在页面顶部

**Comment by hexianqiao3755** [comment]
@lqjymt 在GoodsInfoFragment里面调用一下这个sv_goods_info.smoothScrollTo(0, 0);
让scrollview手动停留在顶部试试
