### ISSUE TITLE
你好，我测试了，demo也有问题的

### ISSUE THREAD

**Issue by cancanw** [hexianqiao3755/GoodsInfoPage#5]
你好，我测试了，demo也有问题的，是给fragment的item里面的控件添加点击事件的时候，如果他的item控件比较复杂一点，点击事件很多，有时候往上滑动的时候，就会在没滑倒顶部的情况下把上面的整个控件都拉下来了。应该是焦点问题，可是怎么解决呢？我试过了 getParent().getParent().requestDisallowInterceptTouchEvent(false);这个方法，但是因为下面的焦点比较多，所以还是会出现这样的问题。。。有办法解决么？

**Comment by hexianqiao3755** [comment]
demo里面所使用的WebView、ListView之类的, 我都是通过自定义的形式来解决了冲突和焦点问题,  你那有问题, 是你有新加别的控件进去吗, 没有用我那定义的吗

**Comment by cancanw** [comment]
可以加个qq说一下么？我给你看效果，就直接在这个listview的item控件上加了个setonclicklintener之后，有时候就会出现这个问题。更不用说我再加其他控件的时候了。QQ：767906144

**Comment by hexianqiao3755** [comment]
加不了

**Comment by cancanw** [comment]
直接随便输个东西就申请就加就行了吧。。。或者我加你。。。
