### ISSUE TITLE
你好，下半部分向上滚动时候，不能到最第一行位置怎么办

### ISSUE THREAD

**Issue by Zhangxd77** [hexianqiao3755/GoodsInfoPage#9]
我是下半部分是个fragment里面是webview界面，weview里面内容很多时候，向上滑动直到看见上拉查看图文详情哪里，下面webview内容还是在第二三行位置，不能滑动到最开始位置怎么把

**Comment by Zhangxd77** [comment]
![_20180716154034](https://user-images.githubusercontent.com/20806535/42747370-b6df53e4-890e-11e8-90bd-1bad2efa9210.png)

**Comment by hexianqiao3755** [comment]
@Zhangxd77 
你改过原来的布局文件吗

**Comment by Zhangxd77** [comment]
改了，是在原来自己项目中写的，但是我进行对比没找到什么问题。您知道为什么吗？

**Comment by hexianqiao3755** [comment]
你用我的demo来改成你的webview试试吧, 我那个应该不会有这种问题的

**Comment by Zhangxd77** [comment]
我是用的腾讯tbs x5的webview，在这上面按照您的进行了修改，也不好使，把你的webview拿来就行，太奇怪了。但是图片加载不出来，

**Comment by hexianqiao3755** [comment]
@Zhangxd77 图片加载不出来 你试试把我webview那里的blockNetworkImage = true 去掉试试
